name: 'DevSkim'
description: 'Run DevSkim Code Analysis'
inputs:
  directory-to-scan:
    description: 'The sub directory of the repository root to scan. Repository root used by default.'
    required: false
    default: ''
  should-scan-archives:
    description: 'Optionally scan the contents of archives.'
    required: false
    default: false
  output-filename:
    description: 'The filename for the output.'
    required: false
    default: "devskim-results.sarif"
branding:
  icon: 'check-square'  
  color: 'green'  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.directory-to-scan }}
    - ${{ inputs.should-scan-archives }}
    - ${{ inputs.output-filename }}
    - ${{ inputs.output-directory }}
